baseURL: 
languageCode: en-us
title: rohanarni.com
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "Rohan Arni"
    subtitle: "Hi there! I’m a freshman at High Technology High School. I’m a programmer, musician, scientist and writer. I play the trumpet and the piano. You can find my code on my GitHub, and you can find my writing at my blog on Medium."
    imageUrl: img/profile.png
    buttons:
      - name: Blog
        url: "/posts"
      - name: Github
        url: "https://github.com/rtenacity"

      
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: posts
      name: Posts
      url: /Posts/
      weight: 20
    - identifier:  
      name: Archives
      url: /archives/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 40
    - identifier: about
      name: About
      url: /about/
      weight: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary